Restored init S10setup, added setup and mac_sn.

diff --git a/src/ltib-mect-config.patch b/src/ltib-mect-config.patch
--- a/src/ltib-mect-config.patch
+++ b/src/ltib-mect-config.patch
@@ -17059,102 +17059,272 @@ diff -urN '--exclude=.config.old' '--exclude=*.config.dev' '--exclude=*.bak' '--
 diff -urN '--exclude=.config.old' '--exclude=*.config.dev' '--exclude=*.bak' '--exclude=*.swp' ltib.reference/config/platform/imx/merge/etc/rc.d/init.d/S10setup ltib/config/platform/imx/merge/etc/rc.d/init.d/S10setup
 --- ltib.reference/config/platform/imx/merge/etc/rc.d/init.d/S10setup
 +++ ltib/config/platform/imx/merge/etc/rc.d/init.d/S10setup
-@@ -0,0 +1,95 @@
+@@ -0,0 +1,265 @@
 +#!/bin/sh
++#
++# Load a new setup from USB or reset the PLC/CAN configurations.
++#
++
++countsys=0
++
++mntdir=/tmp/mnt
++
++LOCAL_ETC_DIR="/local/etc/sysconfig"
++
++logfile=$mntdir/update.log
++UPDATE_DESCR_FILE=/local/kindofupdate.lck
 +
 +start() {
-+        # Check if we are updating the system, if yes wait
-+        usb_string=`df | cut -d ' ' -f1 | grep /dev/sd`
-+        while test "${usb_string:0:7}" == "/dev/sd"; do
-+                sleep 2
-+                echo "waiting for USB disk removal..."
++	sleep 1
++	rm -f $UPDATE_DESCR_FILE
++	echo -n "Checking for configuration USB key...  "
++        if [ -e /sys/block/sda/sda1 ] || [ -e /sys/block/sda ]
++        then
++           
++	        [ -e /sys/block/sda/sda1 ] && usbdev=/dev/sda1
++		[ -d $mntdir ] || { mntdir=/tmp/mnt; /bin/mkdir $mntdir; }
++		[ -d $mntdir ] || exit 1
++		echo "Found scsi device: $usb_string" | tee -a $logfile
++		if /bin/mount -orw $usbdev $mntdir 2>$logfile
++		then
++			rm -f $logfile
++			echo "current mount point is $usbdev" | tee -a $logfile
++			/etc/rc.d/init.d/autoexec stop >/dev/null 2>&1
++			if [ -x /local/flash/root/splash ]
++			then
++				# ts variable
++				export TSLIB_CONFFILE=/usr/etc/ts.conf
++				export TSLIB_PLUGINDIR=/usr/lib/ts
++				export TSLIB_TSDEVICE=/dev/input/ts0
++				export TSLIB_CONSOLEDEVICE=none
++				export TSLIB_CALIBFILE=$LOCAL_ETC_DIR/pointercal
 +
-+                usb_string=`df | cut -d ' ' -f1 | grep /dev/sd`
-+        done
-+        echo "No ongoing update, continuing."
++				# qt variable
++				export QWS_MOUSE_PROTO=tslib:$TSLIB_TSDEVICE
++				export QT_QWS_FONTDIR=/usr/lib/fonts
++				export POINTERCAL_FILE=$TSLIB_CALIBFILE
 +
-+        # Touchscreen variables
-+        export TSLIB_CONFFILE=/usr/etc/ts.conf
-+        export TSLIB_PLUGINDIR=/usr/lib/ts
-+        export TSLIB_TSDEVICE=/dev/input/ts0
-+        export TSLIB_CONSOLEDEVICE=none
-+        export TSLIB_CALIBFILE=/etc/pointercal
++				/local/flash/root/splash -qws --text "<font color=\"red\"><h1>Found an update...</h1>" --dimension 12 >/dev/null 2>&1 &
++			fi
++		else
++			if [ -x /local/flash/root/splash ]
++			then
++				/local/flash/root/splash -qws --text "<font color=\"red\"><h1>Sysupdate status:</h1><BR>`cat $logfile`" --dimension 12 >/dev/null 2>&1
++			fi
++		fi
++	else
++		echo "no usb key found in dmesg"
++		echo "exit from configuration script"
++		return
++	fi
 +
-+        # Qt variables
-+        export QWS_MOUSE_PROTO=tslib:$TSLIB_TSDEVICE
-+        export QT_QWS_FONTDIR=/usr/lib/fonts
-+        export POINTERCAL_FILE=$TSLIB_CALIBFILE
++	echo -n "Starting the configuration process...  "
++	if [ -f $mntdir/reset.conf ]
++	then
++		echo " Resetting all!" | tee -a $logfile
++		/bin/mount -orw,remount $mntdir 2>/dev/null || { echo ""; echo "Cannot mount the USB device RW.  Aborting device reset." | tee -a $logfile; return; }
++		/bin/rm -f $mntdir/reset.conf
 +
-+        # Set display brightness
-+        brctrl="/sys/devices/platform/mxs-bl.0/backlight/mxs-bl/brightness"
-+        if test -r /local/etc/sysconfig/brightness; then
-+                source /local/etc/sysconfig/brightness
-+        else
-+                echo 70 > "$brctrl"
-+        fi
-+        echo "Brightness set to `cat \"$brctrl\"`"
++		# Just apply factory defaults
++		FACTORY_DATA="/local/factory_data.tar.gz"
++		if [ -e $FACTORY_DATA ]
++		then
++			tar xzf /local/$FACTORY_DATA -C /
++			if [ $? == 0 ]
++			then
++				chown root:root -R /local
++				#reset also network configuration and put factory_test with exe permission
++				chmod +x /local/root/factory_test
++				sed -i /IPADDR0/d  "$LOCAL_ETC_DIR/net.conf"
++				sed -i /NETMASK0/d  "$LOCAL_ETC_DIR/net.conf"
++				sed -i /GATEWAY0/d  "$LOCAL_ETC_DIR/net.conf"
++				sed -i /NAMESERVER01/d  "$LOCAL_ETC_DIR/net.conf"
++				sed -i /NAMESERVER02/d  "$LOCAL_ETC_DIR/net.conf"
++				sed -i '2i\IPADDR0=192.168.5.211' "$LOCAL_ETC_DIR/net.conf"
++				sed -i '3i\NETMASK0=255.255.255.0' "$LOCAL_ETC_DIR/net.conf"
++				sed -i '4i\GATEWAY0=192.168.5.10' "$LOCAL_ETC_DIR/net.conf"
++				sed -i '5i\NAMESERVER01=' "$LOCAL_ETC_DIR/net.conf"
++				sed -i '6i\NAMESERVER02=' "$LOCAL_ETC_DIR/net.conf"
 +
-+        # Calibrate touchscreen, if needed
-+        if test ! -e $TSLIB_CALIBFILE; then
-+                if test -x /usr/bin/ts_calibrate; then
-+                        echo -n "Starting touch screen calibration. "
++				echo "The target has been reset." | tee -a $logfile
++				echo "RESET" >> $UPDATE_DESCR_FILE
++			else
++				echo "Error in restoring defaults" | tee -a $logfile
++			fi
++		else
++			echo "Error missing factory data" | tee -a $logfile
++		fi
 +
-+                        /usr/bin/ts_calibrate
-+                        sync
++		#Eventually add other configuration files to be removed for reset operations
++		echo " Reset done!" | tee -a $logfile
 +
-+                        echo "Calbration completed."
-+                else
-+                        echo "Touchscreen calibration program not found."
-+                fi
-+        fi
++	elif [ `ls /local | grep sysupdate | wc -l` -gt  1 ]
++	then
 +
++		echo "Error multiple sysupdate file." | tee -a $logfile
 +
-+    if [ ! -e /etc/mac.conf -o `grep -c MAC0 /etc/mac.conf` -eq 0 -o ! -e /etc/serial.conf ]
-+    then
-+        # Touchscreen variables
-+        export TSLIB_CONFFILE=/usr/etc/ts.conf
-+        export TSLIB_PLUGINDIR=/usr/lib/ts
-+        export TSLIB_TSDEVICE=/dev/input/ts0
-+        export TSLIB_CONSOLEDEVICE=none
-+        export TSLIB_CALIBFILE=/local/etc/sysconfig/pointercal
-+        # Qt variables
-+        export QWS_MOUSE_PROTO=tslib:$TSLIB_TSDEVICE
-+        export QT_QWS_FONTDIR=/usr/lib/fonts
-+        export POINTERCAL_FILE=$TSLIB_CALIBFILE
++	elif [ `ls /local | grep sysupdate | wc -l` -eq  1 ]
++	then
 +
-+        # Ask for MAC address and for serial number
-+        /usr/bin/mac_sn -qws
-+    fi
++		echo " Found one sysupdate!" | tee -a $logfile
++		countsys=1
++		sysupdatename=`ls /local | grep sysupdate`
++		/bin/mount -orw,remount / 2>/dev/null || { echo ""; echo "Cannot mount the root RW.  Aborting update process." | tee -a $logfile; return; }
++		/usr/bin/dos2unix /local/$sysupdatename 2>&1 | tee -a $logfile
++		/bin/sh /local/$sysupdatename 2>&1 | tee -a $logfile
 +
++		if [ $? == 0 ]
++		then
++			echo " Update '/local/$sysupdatename' applied!!!" | tee -a $logfile
++			rm -f /local/$sysupdatename
++			echo "SYSUPDATE" >> $UPDATE_DESCR_FILE
++		else
++			echo " Cannot update '/local/$sysupdatename'." | tee -a $logfile
++		fi
++
++	elif [ `ls $mntdir | grep sysupdate_ | wc -l` -gt  1 ]
++	then
++
++		echo "Error multiple sysupdate file." | tee -a $logfile
++
++	elif [ `ls $mntdir | grep sysupdate_ | wc -l` -eq  1 ]
++	then
++
++		echo " Found one sysupdate!" | tee -a $logfile
++		countsys=1
++		sysupdatename=`ls $mntdir | grep sysupdate_`
++		/bin/mount -orw,remount / 2>/dev/null || { echo ""; echo "Cannot mount the root RW.  Aborting update process." | tee -a $logfile; return; }
++		/usr/bin/dos2unix $mntdir/$sysupdatename 2>&1 | tee -a $logfile
++		/bin/sh $mntdir/$sysupdatename 2>&1 | tee -a $logfile
++		if [ $? == 0 ]
++		then
++			echo " Update '$mntdir/$sysupdatename' applied!!!" | tee -a $logfile
++			echo "SYSUPDATE" >> $UPDATE_DESCR_FILE
++		else
++			echo " Cannot update '/local/$sysupdatename'." | tee -a $logfile
++		fi
++
++	elif [ -f $mntdir/sysupdate.sh ] && [ $countsys -eq 0 ]
++	then
++
++		echo " Performing standard sysupdate!" | tee -a $logfile
++		/bin/mount -orw,remount / 2>/dev/null || { echo ""; echo "Cannot mount the root RW.  Aborting update process."; return; }
++		/usr/bin/dos2unix $mntdir/sysupdate.sh 2>&1 | tee -a $logfile
++		/bin/sh $mntdir/sysupdate.sh 2>&1 | tee -a $logfile
++		if [ $? == 0 ]
++		then
++			echo " Update '$mntdir/sysupdate.sh' applied!!!" | tee -a $logfile
++			echo "SYSUPDATE" >> $UPDATE_DESCR_FILE
++		else
++			echo " Cannot update '$mntdir/sysupdate.sh'." | tee -a $logfile
++		fi
++
++	else
++		# Perform any other configurations
++		/bin/mount -orw,remount $mntdir 2>/dev/null || { echo ""; echo "Cannot mount the USB device RW. Configuration files will be not deleted."; }
++
++		if [ -f $mntdir/application.conf ]
++		then
++			echo " Found a new configuration file '$mntdir/application.conf'" | tee -a $logfile
++			/usr/bin/dos2unix $mntdir/application.conf 2>&1 | tee -a $logfile
++			/bin/cp $mntdir/application.conf $LOCAL_ETC_DIR 2>&1 | tee -a $logfile
++			echo " Configuration file '$mntdir/application.conf' updated!" | tee -a $logfile
++			echo "APPLICATION CONF" >> $UPDATE_DESCR_FILE
++		fi
++		if [ -f $mntdir/atn01.conf ]
++		then
++			echo " Found a new configuration file '$mntdir/atn01.conf'" | tee -a $logfile
++			/usr/bin/dos2unix $mntdir/atn01.conf 2>&1 | tee -a $logfile
++			/bin/cp $mntdir/atn01.conf $LOCAL_ETC_DIR 2>&1 | tee -a $logfile
++			echo " Configuration file '$mntdir/atn01.conf' updated!" | tee -a $logfile
++			echo "ATN01 CONF" >> $UPDATE_DESCR_FILE
++		fi
++		if [ -f $mntdir/Crosstable.csv ]
++		then
++			echo " Found a new configuration file '$mntdir/Crosstable.csv'" | tee -a $logfile
++			/usr/bin/dos2unix $mntdir/Crosstable.csv 2>&1 | tee -a $logfile
++			/bin/cp $mntdir/Crosstable.csv $LOCAL_ETC_DIR 2>&1 | tee -a $logfile
++			echo " Configuration file '$mntdir/Crosstable.csv' updated!" | tee -a $logfile
++			echo "CROSSTABLE" >> $UPDATE_DESCR_FILE
++		fi
++		if [ -f $mntdir/Commpar.csv ]
++		then
++			echo " Found a new configuration file '$mntdir/Commpar.csv'" | tee -a $logfile
++			/usr/bin/dos2unix $mntdir/Commpar.csv 2>&1 | tee -a $logfile
++			/bin/cp $mntdir/Commpar.csv $LOCAL_ETC_DIR 2>&1 | tee -a $logfile
++			echo " Configuration file '$mntdir/Commpar.csv' updated!" | tee -a $logfile
++			echo "COMMPAR" >> $UPDATE_DESCR_FILE
++		fi
++		if [ -f $mntdir/Alarms.csv ]
++		then
++			echo " Found a new configuration file '$mntdir/Alarms.csv'" | tee -a $logfile
++			/usr/bin/dos2unix $mntdir/Alarms.csv 2>&1 | tee -a $logfile
++			/bin/cp $mntdir/Alarms.csv $LOCAL_ETC_DIR 2>&1 | tee -a $logfile
++			echo " Configuration file '$mntdir/Alarms.csv' updated!" | tee -a $logfile
++			echo "ALARMS" >> $UPDATE_DESCR_FILE
++		fi
++		if [ -f $mntdir/net.conf ]
++		then
++			echo " Found a new network configuration file '$mntdir/net.conf'" | tee -a $logfile
++			/usr/bin/dos2unix $mntdir/net.conf 2>&1 | tee -a $logfile
++			/bin/cp $mntdir/net.conf $LOCAL_ETC_DIR 2>&1 | tee -a $logfile
++			echo " Network configuration file '$mntdir/net.conf' updated!" | tee -a $logfile
++			echo "NETWORK" >> $UPDATE_DESCR_FILE
++		fi
++		if [ -f $mntdir/autoexec ]
++		then
++			echo " Found a new autoexec file file '$mntdir/autoexec'" | tee -a $logfile
++			/bin/mount -orw,remount / 2>/dev/null || { echo ""; echo "Cannot mount the root RW.  Aborting autoexec update process."; return; }
++			/usr/bin/dos2unix $mntdir/autoexec 2>&1 | tee -a $logfile
++			/bin/cp $mntdir/autoexec /usr/bin/autoexec 2>&1 | tee -a $logfile
++			/bin/mount -oro,remount / 2>&1 | tee -a $logfile
++			echo " Autoexec file '$mntdir/autoexec' updated!" | tee -a $logfile
++			echo "AUTOEXEC" >> $UPDATE_DESCR_FILE
++		fi
++	fi
++	#Sync for ubifs
++	/bin/sync
++	if [ -n "$usb_string" ]
++	then
++		/bin/umount $mntdir
++	fi
++
++	if [ -x /local/flash/root/splash ]
++	then
++		/local/flash/root/splash -qws --text "<font color=\"red\"><h1>Sysupdate status:</h1><BR>`cat $logfile`" --dimension 12 >/dev/null 2>&1
++	fi
++
++	/etc/rc.d/init.d/autoexec start >/dev/null 2>&1
++	echo "  Done."
 +}
 +
 +stop() {
++#echo -n "Shutting down 'S10setup'... "
++#start-stop-daemon  -K -q -x /usr/bin/S10setup
++echo "Done."
 +}
 +
 +restart() {
-+        stop
-+        start
++stop
++sleep 1
++start
 +}
 +
 +case "$1" in
-+        start)
-+                start
-+        ;;
-+
-+        stop)
-+                stop
-+        ;;
-+
-+        restart)
-+                restart
-+        ;;
-+
-+        *)
-+                echo $"Usage: $0 {start|stop|restart}"
-+                        exit 1
-+        ;;
++start)
++	start
++;;
++stop)
++	stop
++;;
++restart)
++	restart
++;;
++*)
++  echo $"Usage: $0 {start|stop|restart}"
++		exit 1
++	;;
 +esac
-+
 diff -urN '--exclude=.config.old' '--exclude=*.config.dev' '--exclude=*.bak' '--exclude=*.swp' ltib.reference/config/platform/imx/merge/etc/rc.d/init.d/autoexec ltib/config/platform/imx/merge/etc/rc.d/init.d/autoexec
 --- ltib.reference/config/platform/imx/merge/etc/rc.d/init.d/autoexec
 +++ ltib/config/platform/imx/merge/etc/rc.d/init.d/autoexec
@@ -17305,6 +17475,33 @@ diff -urN '--exclude=.config.old' '--exclude=*.config.dev' '--exclude=*.bak' '--
 +	*)
 +		echo $"Usage: $0 {start|stop|restart}"
 +			exit 1
++	;;
++esac
+diff -urN '--exclude=.config.old' '--exclude=*.config.dev' '--exclude=*.bak' '--exclude=*.swp' ltib.reference/config/platform/imx/merge/etc/rc.d/init.d/mac_sn ltib/config/platform/imx/merge/etc/rc.d/init.d/mac_sn
+--- ltib.reference/config/platform/imx/merge/etc/rc.d/init.d/mac_sn
++++ ltib/config/platform/imx/merge/etc/rc.d/init.d/mac_sn
+@@ -0,0 +1,23 @@
++#!/bin/sh
++
++start() {
++	/usr/bin/mac_sn &
++}
++
++case "$1" in
++	start)
++		start
++	;;
++
++	stop)
++	;;
++
++	restart)
++		start
++	;;
++
++	*)
++		echo $"Usage: $0 {start|stop|restart}"
++		exit 1
 +	;;
 +esac
 diff -urN '--exclude=.config.old' '--exclude=*.config.dev' '--exclude=*.bak' '--exclude=*.swp' ltib.reference/config/platform/imx/merge/etc/rc.d/init.d/network ltib/config/platform/imx/merge/etc/rc.d/init.d/network
@@ -17728,6 +17925,105 @@ diff -urN '--exclude=.config.old' '--exclude=*.config.dev' '--exclude=*.bak' '--
 +        exit 1
 +    ;;
 +esac
+diff -urN '--exclude=.config.old' '--exclude=*.config.dev' '--exclude=*.bak' '--exclude=*.swp' ltib.reference/config/platform/imx/merge/etc/rc.d/init.d/setup ltib/config/platform/imx/merge/etc/rc.d/init.d/setup
+--- ltib.reference/config/platform/imx/merge/etc/rc.d/init.d/setup
++++ ltib/config/platform/imx/merge/etc/rc.d/init.d/setup
+@@ -0,0 +1,95 @@
++#!/bin/sh
++
++start() {
++        # Check if we are updating the system, if yes wait
++        usb_string=`df | cut -d ' ' -f1 | grep /dev/sd`
++        while test "${usb_string:0:7}" == "/dev/sd"; do
++                sleep 2
++                echo "waiting for USB disk removal..."
++
++                usb_string=`df | cut -d ' ' -f1 | grep /dev/sd`
++        done
++        echo "No ongoing update, continuing."
++
++        # Touchscreen variables
++        export TSLIB_CONFFILE=/usr/etc/ts.conf
++        export TSLIB_PLUGINDIR=/usr/lib/ts
++        export TSLIB_TSDEVICE=/dev/input/ts0
++        export TSLIB_CONSOLEDEVICE=none
++        export TSLIB_CALIBFILE=/etc/pointercal
++
++        # Qt variables
++        export QWS_MOUSE_PROTO=tslib:$TSLIB_TSDEVICE
++        export QT_QWS_FONTDIR=/usr/lib/fonts
++        export POINTERCAL_FILE=$TSLIB_CALIBFILE
++
++        # Set display brightness
++        brctrl="/sys/devices/platform/mxs-bl.0/backlight/mxs-bl/brightness"
++        if test -r /local/etc/sysconfig/brightness; then
++                source /local/etc/sysconfig/brightness
++        else
++                echo 70 > "$brctrl"
++        fi
++        echo "Brightness set to `cat \"$brctrl\"`"
++
++        # Calibrate touchscreen, if needed
++        if test ! -e $TSLIB_CALIBFILE; then
++                if test -x /usr/bin/ts_calibrate; then
++                        echo -n "Starting touch screen calibration. "
++
++                        /usr/bin/ts_calibrate
++                        sync
++
++                        echo "Calbration completed."
++                else
++                        echo "Touchscreen calibration program not found."
++                fi
++        fi
++
++
++    if [ ! -e /etc/mac.conf -o `grep -c MAC0 /etc/mac.conf` -eq 0 -o ! -e /etc/serial.conf ]
++    then
++        # Touchscreen variables
++        export TSLIB_CONFFILE=/usr/etc/ts.conf
++        export TSLIB_PLUGINDIR=/usr/lib/ts
++        export TSLIB_TSDEVICE=/dev/input/ts0
++        export TSLIB_CONSOLEDEVICE=none
++        export TSLIB_CALIBFILE=/local/etc/sysconfig/pointercal
++        # Qt variables
++        export QWS_MOUSE_PROTO=tslib:$TSLIB_TSDEVICE
++        export QT_QWS_FONTDIR=/usr/lib/fonts
++        export POINTERCAL_FILE=$TSLIB_CALIBFILE
++
++        # Ask for MAC address and for serial number
++        /usr/bin/mac_sn -qws
++    fi
++
++}
++
++stop() {
++}
++
++restart() {
++        stop
++        start
++}
++
++case "$1" in
++        start)
++                start
++        ;;
++
++        stop)
++                stop
++        ;;
++
++        restart)
++                restart
++        ;;
++
++        *)
++                echo $"Usage: $0 {start|stop|restart}"
++                        exit 1
++        ;;
++esac
++
 diff -urN '--exclude=.config.old' '--exclude=*.config.dev' '--exclude=*.bak' '--exclude=*.swp' ltib.reference/config/platform/imx/merge/etc/rc.d/rc.local ltib/config/platform/imx/merge/etc/rc.d/rc.local
 --- ltib.reference/config/platform/imx/merge/etc/rc.d/rc.local
 +++ ltib/config/platform/imx/merge/etc/rc.d/rc.local
